var topAPG = [
  list_id: 2,
  league: "NBA",
  keywords: "top apg nba assists passing",
  description: "Top APG averages all time",
  player: 
  {
    "rank":1,
    "last_name":"Johnson",
    "first_name":"Magic",
    "apg":11.19
  },
  {
    "rank":2,
    "last_name":"Stockton",
    "first_name":"John",
    "apg":10.51
  },
  {
    "rank":3,
    "last_name":"Paul",
    "first_name":"Chris",
    "apg":9.92
  },
  {
    "rank":4,
    "last_name":"Robertson",
    "first_name":"Oscar",
    "apg":9.51
  },
  {
    "rank":5,
    "last_name":"Thomas",
    "first_name":"Isiah",
    "apg":9.26
  },
  {
    "rank":6,
    "last_name":"Johnson",
    "first_name":"Kevin",
    "apg":9.13
  },
  {
    "rank":7,
    "last_name":"Kidd",
    "first_name":"Jason",
    "apg":8.69
  },
  {
    "rank":8,
    "last_name":"Wall",
    "first_name":"John",
    "apg":8.61
  },
  {
    "rank":9,
    "last_name":"Williams",
    "first_name":"Deron",
    "apg":8.53
  },
  {
    "rank":10,
    "last_name":"Nash",
    "first_name":"Steve",
    "apg":8.49
  }
]