var topBPG = [
  list_id: 3,
  league: "NBA",
  keywords: "top bpg nba blocks",
  description: "Top blocks per game averages all time",
  player: 
  {
    "rank":1,
    "last_name":"Eaton",
    "first_name":"Mark",
    "bpg":3.5
  },
  {
    "rank":2,
    "last_name":"Bol",
    "first_name":"Manute",
    "bpg":3.34
  },
  {
    "rank":3,
    "last_name":"Olajuwon",
    "first_name":"Hakeem",
    "bpg":3.09
  },
  {
    "rank":4,
    "last_name":"Robinson",
    "first_name":"David",
    "bpg":2.99
  },
  {
    "rank":5,
    "last_name":"Smith",
    "first_name":"Elmore",
    "bpg":2.9
  },
  {
    "rank":6,
    "last_name":"Mourning",
    "first_name":"Alonzo",
    "bpg":2.81
  },
  {
    "rank":7,
    "last_name":"Mutombo",
    "first_name":"Dikembe",
    "bpg":2.75
  },
  {
    "rank":8,
    "last_name":"Ibaka",
    "first_name":"Serge",
    "bpg":2.58
  },
  {
    "rank":9,
    "last_name":"Abdul-Jabbar",
    "first_name":"Kareem",
    "bpg":2.57
  },
  {
    "rank":10,
    "last_name":"Bradley",
    "first_name":"Shawn",
    "bpg":2.55
  }
]