var fieldGoalPercentage = [
  list_id: 4,
  league: "NBA",
  keywords: "top field goal percentage nba shooting scoring",
  description: "Top field goal percentage all time",
  player:
  {
    "rank":1,
    "last_name":"Gilmore",
    "first_name":"Artis",
    "fieldGoalPercentage":0.599
  },
  {
    "rank":2,
    "last_name":"Chandler",
    "first_name":"Tyson",
    "fieldGoalPercentage":0.5906
  },
  {
    "rank":3,
    "last_name":"O'Neal",
    "first_name":"Shaquille",
    "fieldGoalPercentage":0.5823
  },
  {
    "rank":4,
    "last_name":"West",
    "first_name":"Mark",
    "fieldGoalPercentage":0.5803
  },
  {
    "rank":5,
    "last_name":"Howard",
    "first_name":"Dwight",
    "fieldGoalPercentage":0.5785
  },
  {
    "rank":6,
    "last_name":"Johnson",
    "first_name":"Steve",
    "fieldGoalPercentage":0.5722
  },
  {
    "rank":7,
    "last_name":"Dawkins",
    "first_name":"Darryl",
    "fieldGoalPercentage":0.572
  },
  {
    "rank":8,
    "last_name":"Donaldson",
    "first_name":"James",
    "fieldGoalPercentage":0.5706
  },
  {
    "rank":9,
    "last_name":"Outlaw",
    "first_name":"Bo",
    "fieldGoalPercentage":0.5673
  },
  {
    "rank":10,
    "last_name":"Ruland",
    "first_name":"Jeff",
    "fieldGoalPercentage":0.5637
  }
]