var ftPercentage = [
  list_id: 5,
  league: "NBA",
  keywords: "top free throw freethrow percentage nba shooting scoring",
  description: "Top free throw percentage all time",
  player:
  {
    "rank":1,
    "last_name":"Nash",
    "first_name":"Steve",
    "ftPercentage":0.9043
  },
  {
    "rank":2,
    "last_name":"Price",
    "first_name":"Mark",
    "ftPercentage":0.9039
  },
  {
    "rank":3,
    "last_name":"Barry",
    "first_name":"Rick",
    "ftPercentage":0.8998
  },
  {
    "rank":4,
    "last_name":"Curry",
    "first_name":"Stephen",
    "ftPercentage":0.8984
  },
  {
    "rank":5,
    "last_name":"Stojakovic",
    "first_name":"Peja",
    "ftPercentage":0.8948
  },
  {
    "rank":6,
    "last_name":"Billups",
    "first_name":"Chauncey",
    "ftPercentage":0.894
  },
  {
    "rank":7,
    "last_name":"Allen",
    "first_name":"Ray",
    "ftPercentage":0.8939
  },
  {
    "rank":8,
    "last_name":"Murphy",
    "first_name":"Calvin",
    "ftPercentage":0.8916
  },
  {
    "rank":9,
    "last_name":"Skiles",
    "first_name":"Scott",
    "ftPercentage":0.8891
  },
  {
    "rank":10,
    "last_name":"Miller",
    "first_name":"Reggie",
    "ftPercentage":0.8877
  }
]