var threePointPercentage = [
  list_id: 8,
  league: "NBA",
  keywords: "top three point threepoint shooting scoring",
  description: "Top three point percentage all time",
  player:
  {
    "rank":1,
    "last_name":"Kerr",
    "first_name":"Steve",
    "threePointPercentage":0.454
  },
  {
    "rank":2,
    "last_name":"Davis",
    "first_name":"Hubert",
    "threePointPercentage":0.4409
  },
  {
    "rank":3,
    "last_name":"Petrovic",
    "first_name":"Drazen",
    "threePointPercentage":0.4374
  },
  {
    "rank":4,
    "last_name":"Curry",
    "first_name":"Stephen",
    "threePointPercentage":0.4347
  },
  {
    "rank":5,
    "last_name":"Kapono",
    "first_name":"Jason",
    "threePointPercentage":0.4336
  },
  {
    "rank":6,
    "last_name":"Novak",
    "first_name":"Steve",
    "threePointPercentage":0.4328
  },
  {
    "rank":7,
    "last_name":"Korver",
    "first_name":"Kyle",
    "threePointPercentage":0.4314
  },
  {
    "rank":8,
    "last_name":"Legler",
    "first_name":"Tim",
    "threePointPercentage":0.4312
  },
  {
    "rank":9,
    "last_name":"Nash",
    "first_name":"Steve",
    "threePointPercentage":0.4278
  },
  {
    "rank":10,
    "last_name":"Armstrong",
    "first_name":"B.J.",
    "threePointPercentage":0.425
  }
]